spring.mvc.favicon.enabled: false
server.port: 8081

logging.level:
  org.springframework: WARN
  org.hibernate: WARN
  org.springframework.web: DEBUG

stopmotion:
  cameras:
    - ip: "192.168.1.44"
      name: "Camera 1"

storage.location: "/tmp/stopmotion"

---
spring:
  profiles: home
  
stopmotion:
  cameras:
    - ip: "192.168.1.23"
      name: "Camera 1"