spring.mvc.favicon.enabled: false
server.port: 8081

spring.servlet.multipart:
  enabled: true
  file-size-threshold: "2KB"
  max-file-size: "200MB"
  max-request-size: "215MB"


logging.level:
  org.springframework: WARN
  org.hibernate: WARN
  org.springframework.web: INFO
  org.webjars: DEBUG

stopmotion:
  location: "/tmp/stopmotion"
  cameras:
    - name: "Camera 1"
      host: "192.168.1.44"
      port: 8000
      robotPort: 8080
      path: "/stream.mjpg"
    - name: "Camera 2"
      host: "192.168.1.44"
      port: 8000
      path: "/stream.mjpg"
      robotPort: 8080
---
spring.profiles: cern
stopmotion:
  cameras:
    - name: "Camera 1"
      host: "ergo-nine.cern.ch"
      port: 8000
      robotPort: 8080
      path: "/stream.mjpg"
    - name: "Camera 2"
      host: "ergo-nine.cern.ch"
      port: 8000
      robotPort: 8080
      path: "/stream.mjpg"
